apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec: {}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/christianh814/kargo-simple-demo
      branch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: default-promote
  namespace: kargo-demo
spec:
  vars:
  - name: repoURL
  - name: sourceBranch
  - name: targetBranch

  steps:

  - uses: git-clone
    as: clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.sourceBranch }}
        path: ./src
      - branch: stage/${{ vars.targetBranch }}
        create: true
        path: ./dst

  - uses: git-clear
    as: clear
    config:
      path: ./dst

  - uses: kustomize-build
    as: build-manifests
    config:
      path: ./src/app/stages/${{ vars.targetBranch }}
      outPath: ./dst/${{ vars.targetBranch }}.yaml

  - uses: git-commit
    as: commit
    config:
      path: ./dst
      messageFromSteps:
      - build-manifests

  - uses: git-push
    as: push
    config:
      path: ./dst
      targetBranch: stage/${{ vars.targetBranch }}

  - uses: argocd-update
    config:
      apps:
      - name: kargo-demo-${{ vars.targetBranch }}
        namespace: argocd
        sources:
        - repoURL: ${{ vars.repoURL }}
          desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: repoURL
        value: https://github.com/christianh814/kargo-simple-demo
      - name: sourceBranch
        value: main
      - name: targetBranch
        value: test
      steps:
      - task:
          name: default-promote
        as: promote-to-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      vars:
      - name: repoURL
        value: https://github.com/christianh814/kargo-simple-demo
      - name: sourceBranch
        value: main
      - name: targetBranch
        value: uat
      steps:
      - task:
          name: default-promote
        as: promote-to-uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: repoURL
        value: https://github.com/christianh814/kargo-simple-demo
      - name: sourceBranch
        value: main
      - name: targetBranch
        value: prod
      steps:
      - task:
          name: default-promote
        as: promote-to-prod
